# ---------------- DATABASE (PostgreSQL) ----------------
# Render var deploy kelyavar he automatic values gheil, local var default values vaprel.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/career_ai}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:SURaj#123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ---------------- SERVER PORT ----------------
# Render sathi ${PORT} garjeche ahe, local sathi 8081 vaprel.
server.port=${PORT:8081}

# ---------------- THYMELEAF ----------------
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# ---------------- OPENROUTER AI ----------------
# Render chya Dashboard madhe OPENROUTER_API_KEY naavane variable add kara.
openrouter.api.key=${OPENROUTER_API_KEY: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}

# ---------------- EMAIL / SMTP ----------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aiicareerapp@gmail.com
# Render var SPRING_MAIL_PASSWORD naavane app password add kara.
spring.mail.password=${SPRING_MAIL_PASSWORD:bewagehjleneoozt}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8