spring.datasource.url=jdbc:mysql://localhost:3306/career_ai
spring.datasource.username=root
spring.datasource.password=SURaj#123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ---------------- SERVER PORT ----------------
server.port=8081


# ---------------- THYMELEAF ----------------
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# File Upload Size Increase
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# ---------------- OPENROUTER AI ----------------
openrouter.api.key=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


# ---------------- EMAIL / SMTP ----------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aiicareerapp@gmail.com
spring.mail.password=bewagehjleneoozt

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8